dist: focal
sudo: true
language: python
services: docker

addons:
  hosts:
    - mariadb.example.com

before_install:
  - export PROJ_PATH=`pwd`
  - chmod +x .travis/script.sh
  - sudo apt-get install software-properties-common
  - sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8
  - sudo add-apt-repository 'deb [arch=amd64,arm64,ppc64el] http://mirrors.accretive-networks.net/mariadb/repo/10.4/ubuntu bionic main'
  - sudo apt-get remove --purge mysql*
  - sudo apt update
  - sudo apt-get install -f libssl-dev libssl1.1
  - sudo apt-get install -f
  - git clone https://github.com/mariadb-corporation/mariadb-connector-c.git ~/.cc_3.1
  - cd ~/.cc_3.1
  - mkdir bld
  - cd bld
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
  - make -j4
  - sudo make install
  - sudo apt-get install -f mariadb-client
  - cd $PROJ_PATH
  - git clone https://github.com/pyenv/pyenv.git ~/.pyenv
  - export PYENV_ROOT="$HOME/.pyenv"
  - export PATH="$PYENV_ROOT/bin:$PATH"
  - echo $PATH
  - eval "$(pyenv init -)"

install:
#  - wget -qO- 'https://github.com/tianon/pgp-happy-eyeballs/raw/master/hack-my-builds.sh' | bash
  # generate SSL certificates
  - chmod +x .travis/gen-ssl.sh
  - chmod +x .travis/build/build.sh
  - chmod +x .travis/build/docker-entrypoint.sh
  - chmod 777 .travis/build/
  - mkdir tmp
  - .travis/gen-ssl.sh mariadb.example.com tmp
  - chmod 777 tmp/*
  - export PROJ_PATH=`pwd`
  - export SSLCERT=$PROJ_PATH/tmp
  - export TEST_SSL_CA_FILE=$SSLCERT/server.crt
  - export TEST_SSL_CLIENT_KEY_FILE=$SSLCERT/client.key
  - export TEST_SSL_CLIENT_CERT_FILE=$SSLCERT/client.crt
  - export MARIADB_PLUGIN_DIR==`mariadb_config --plugindir`
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/mariadb

env:
  global:
  - TEST_PORT=3305
  - TEST_HOST=mariadb.example.com

matrix:
  include:
  - env: PYTHON_VER="3.8.0" SKYSQL=true
  - env: PYTHON_VER="3.8.0" SKYSQL_HA=true MAXSCALE_TEST_DISABLE=true
  - env: PYTHON_VER="3.8.0" DB=mariadb:10.5 DB=mariadb:10.5 MAXSCALE_VERSION=2.5.3 MAXSCALE_TEST_DISABLE=true
  - env: PYTHON_VER="3.8.0" DB=build:10.6
  - env: PYTHON_VER="3.8.0" DB=mariadb:10.5
  - env: PYTHON_VER="3.6.0" DB=mariadb:10.5
  - env: PYTHON_VER="3.8.0" DB=mariadb:10.4
  - env: PYTHON_VER="3.8.0" DB=mariadb:10.3
  - env: PYTHON_VER="3.8.0" DB=mariadb:10.2
  - env: PYTHON_VER="3.8.0" DB=mysql:5.7
  - env: PYTHON_VER="3.8.0" DB=mysql:8.0 ADDITIONAL_CONF=--default-authentication-plugin=mysql_native_password

notifications:
  email: false

script:
  - if [[ "$DB" == build* ]] ; then .travis/build/build.sh; fi
  - if [[ "$DB" == build* ]] ; then docker build -t build:10.6 --label build .travis/build/; fi
  - .travis/script.sh
